Better stream error
wechaty/wechaty-puppet-hostie pull request #95
Opened 2020-11-05 16:33 UTC by windmemory

Related to https://github.com/wechaty/wechaty-puppet-hostie/issues/93

2020-11-05 16:57 UTC, huan requested changes
Thank you very much for this great improvement with streaming with error handlers!

Please remove the `test.dat` and check the file `typed-stream.ts`, then I believe it will be ready to merge.

2020-11-05 16:57 UTC, huan commented on src/stream/typed-stream.ts
> +import {
I believe this file had been deleted by me days ago.

2020-11-06 04:06 UTC, windmemory commented
Updated according to comments :P

2020-11-06 04:07 UTC, huan approved these changes
LGTM

2020-11-06 04:07 UTC, merged

2020-11-06 04:07 UTC, huan commented
Brilliant changes! merged.

2020-11-06 06:57 UTC, windmemory commented
> Brilliant changes! merged.

Thanks for your help on the PR!